name: CI-code-cov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you want to use    

    - name: Install Package in Editable Mode with Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2' # Use the R version you prefer

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: true
        cache-version: 1
        dependencies: 'NA'
        install-pandoc: false
        packages: |
          grf
          causalweight
          mediation

    - name: Install plmed package          
      run: |    
        R -e "pak::pkg_install('ohines/plmed')"

    - name: Install Pytest and Coverage
      run: |
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        pytest --cov=med_bench --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.3.0
      with:
        # token: ${{ secrets.CODECOV_TOKEN }}
        token: 'e4829e41-01da-4d08-9e04-04443da957e3'
        slug: judithabk6/med_bench
        
