name: CI-with-R

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you want to use    

    - name: Install Package in Editable Mode with Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2' # Use the R version you prefer

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: true
        cache-version: 1
        dependencies: 'NA'
        install-pandoc: false
        packages: |
          Matrix@1.6-5
          MASS@7.3-60
          grf
          causalweight
          mediation

    - name: Install plmed package          
      run: |    
        R -e "pak::pkg_install('ohines/plmed')"

    - name: Install Pytest
      run: |
        pip install pytest

    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$(python -m rpy2.situation LD_LIBRARY_PATH):${LD_LIBRARY_PATH}
        pytest
